#define HTTP_CODE_NOT_FOUND 404
#define HTTP_CODE_BAD_REQUEST 400
#define HTTP_CODE_UNAUTHORIZED 401
#define HTTP_CODE_INTERNAL_ERROR 500
#define HTTP_CODE_NOT_IMPLEMENTED 501
#define HTTP_CODE_MOVED 301
#define HTTP_CODE_SUCCESS 200
#define HTTP_CODE_CREATED 201
#define HTTP_CODE_ACCEPTED 202
#define HTTP_CODE_NOT_CONTENT 204

#define getAllHTTPCode()(@[HTTP_CODE_NOT_FOUND,HTTP_CODE_BAD_REQUEST,HTTP_CODE_UNAUTHORIZED,HTTP_CODE_INTERNAL_ERROR,HTTP_CODE_NOT_IMPLEMENTED,HTTP_CODE_MOVED,HTTP_CODE_SUCCESS,HTTP_CODE_CREATED,HTTP_CODE_ACCEPTEDHTTP_CODE_NOT_CONTENT])




